trigger:
- main

pool: ap_vm1_test

variables:
- group: terraform-sp-var-group

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls -la
    whoami

- script: sudo apt install azure-cli -y
  displayName: 'Install azure-cli'

- bash: |
    cd IaC
    terraform init
    terraform apply -var="client_id=$(appId)" -var="client_secret=$(password)" -var="subscription_id=$(subscriptionId)" -var="tenant_id=$(tenant)" --auto-approve
  displayName: 'terraform test'