trigger:
- IaC

pool: ap_vm1_test

parameters:
- name: Action
  displayName: 'Apply or Destroy IaC'
  type: string
  values:
    - apply
    - destroy
  default: apply

variables:
- group: terraform-sp-var-group

stages:
- stage: Install
  jobs:
  - job: InitialJob
    steps:
    - script: |
        ls -la
        whoami
      displayName: 'Show Environment'

    # - script: sudo apt install azure-cli -y
    #   displayName: 'Install azure-cli'

- stage: Build
  jobs:
  - job: BuildDestroyIaC
    steps:
    - bash: |
        cd IaC
        export TF_VAR_sa_key=$(sa_key)
        terraform init
        terraform fmt
        terraform ${{ parameters.Action }} -var="client_id=$(appId)" -var="client_secret=$(password)" -var="subscription_id=$(subscriptionId)" -var="tenant_id=$(tenant)" --auto-approve
      displayName: 'terraform test'